"""empty message

Revision ID: 065d03ecaf64
Revises: ed088de11b7f
Create Date: 2018-02-08 17:53:55.071277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065d03ecaf64'
down_revision = 'ed088de11b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
