"""empty message

Revision ID: e86ca3c55fb7
Revises: bd50c7590a47
Create Date: 2018-01-27 19:42:04.767249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86ca3c55fb7'
down_revision = 'bd50c7590a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_constraint('category_name_key', 'category', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('category_name_key', 'category', ['name'])
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###
